<?php
/**
 * Created by PhpStorm.
 * User: Ion Bogatu
 * Date: 7/9/2018
 * Time: 7:50 PM
 *
 * @var $block \Magento\Backend\Block\Template
 */

$currentlySelectedModule = $this->helper('Ibg\Codegen\Helper\ModuleGenerator')->getCurrentlySelectedModule();
?>

<div data-bind="scope: 'codegen.module'" data-title="Create Module" <?php echo !empty($block->getAdditionalClass()) ? 'data-class="' . $block->getAdditionalClass() . '"' : '';?>>
    <div data-role="messages" class="messages">

    </div>
    <input type="hidden" id="destination" data-bind="value: $parent.currentAction"/>
    <div class="admin__fieldset-wrapper-content" data-bind="css: {active: $parent.currentAction() === 'create'}">
        <div class="fieldset-wrapper-title">
            <strong>
                <span>Create New Module</span>
            </strong>
        </div>
        <fieldset class="admin__fieldset">
            <fieldset class="admin__field">
                <label class="admin__field-label" for="codegen_module_name_create">
                    <span><?php echo __('Module Name'); ?></span>
                </label>

                <div class="admin__field-control">
                    <input class="admin__control-text"
                           type="text"
                           id="codegen_module_name_create"
                           data-bind="event: {focus: function(data, event){ changeModuleAction('create', event) }, change: function(data, event){ changeModuleAction('create', event) } }"
                           maxlength="255">

                    <div class="admin__field-note">
                        <span><?php echo sprintf(__('Module name should match the following pattern: %s. Example <strong>Ibg_Codegen</strong>'), $block->getModuleNameRegEx()); ?></span>
                    </div>
                </div>
            </fieldset>
        </fieldset>
    </div>
    <div class="or-divider short"><span>OR</span></div>
    <div class="admin__fieldset-wrapper-content" data-bind="css: {active: $parent.currentAction() === 'select'}">
        <div class="fieldset-wrapper-title">
            <strong>
                <span>Select Module</span>
            </strong>
        </div>
        <fieldset class="admin__fieldset">
            <fieldset class="admin__field">
                <label class="admin__field-label" for="codegen_module_name_select">
                    <span><?php echo __('Module'); ?></span>
                </label>

                <div class="admin__field-control">
                    <select class="admin__control-select" id="codegen_module_name_select" data-bind="event: {click: function(data, event){ changeModuleAction('select', data) } }, value: $parent.currentModule()">
                        <!-- ko foreach: moduleList -->
                            <option data-bind="text: $data, value: $data"></option>
                        <!-- /ko -->
                    </select>
                </div>
            </fieldset>
        </fieldset>
    </div>
</div>
