<?php
/**
 * Created by PhpStorm.
 * User: Ion Bogatu
 * Date: 6/7/2018
 * Time: 7:40 PM
 *
 * @var $block \Ibg\Codegen\Block\Adminhtml\Globalpage\Block
 */

$currentlySelectedModule = $block->getCurrentlySelectedModule();
$areas = $block->getAreas();
?>

<div id="block_modal" data-submit-url="<?php echo $block->getUrl('codegen/block/createBlock', ['_secure' => true]); ?>" class="codegen_modal hidden">
    <div data-role="spinner" data-component="codegen.block.form" class="admin__data-grid-loading-mask" style="display: block;">
        <div class="spinner">
            <span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span>
        </div>
    </div>
    <div data-role="messages" class="messages">

    </div>

    <div class="admin__fieldset-wrapper-content">
        <div class="fieldset-wrapper-title">
            <strong>
                <span>Create New Block</span>
            </strong>
        </div>
        <fieldset class="admin__fieldset">
            <fieldset class="admin__field">
                <label class="admin__field-label" for="block_area">
                    <span><?php echo __('Area'); ?></span>
                </label>

                <div class="admin__field-control">
                    <select class="admin__control-select" name="block_area" id="block_area">
                        <?php if(!empty($areas)){ ?>
                            <?php foreach($areas as $area){ ?>
                                <option value="<?php echo $area['value']; ?>"><?php echo $area['label']; ?></option>
                            <?php  } ?>
                        <?php  } ?>
                    </select>

                    <div class="admin__field-note">
                        <span><?php echo sprintf(__('Area where the block will be generated.'), $block->getBlockClassNameRegEx()); ?></span>
                    </div>
                </div>
            </fieldset>
            <fieldset class="admin__field">
                <label class="admin__field-label" for="block_class_path">
                    <span><?php echo __('Block Class Path'); ?></span>
                </label>

                <div class="admin__field-control">
                    <div class="admin__field-control-flex">
                        <span class="absolute_path">\<?php echo implode('\\', explode('_', $currentlySelectedModule)); ?>\Block<span class="area"></span>\</span>
                        <input class="admin__control-text" type="text" name="block_class_path" id="block_class_path" maxlength="255">
                    </div>

                    <div class="admin__field-note">
                        <span><?php echo sprintf(__('Block class path should match the following pattern: %s. Examples <strong>Block</strong>, <strong>Component\Child\Block</strong>, <strong>MyBlock</strong>, <strong>MAINBlock</strong>'), $block->getBlockClassNameRegEx()); ?></span>
                        <br/>
                        <span><?php echo sprintf(__('<strong>Hint: </strong>You can also specify the block\'s template file.')); ?></span>
                    </div>
                </div>
            </fieldset>
            <fieldset class="admin__field">
                <label class="admin__field-label" for="block_name_in_layout">
                    <span><?php echo __('Block Name in Layout'); ?></span>
                </label>

                <div class="admin__field-control">
                    <input class="admin__control-text" type="text" name="block_name_in_layout" id="block_name_in_layout" maxlength="255">

                    <div class="admin__field-note">
                        <span><?php echo sprintf(__('Block name in layout should match the following pattern: %s. Examples <strong>block</strong>, <strong>my_block</strong>, <strong>main.block</strong>'), $block->getBlockNameInLayoutRegEx()); ?></span>
                    </div>
                </div>
            </fieldset>
            <!--<fieldset class="admin__field">
                <label class="admin__field-label" for="codegen_module_name_create">
                    <span><?php /*echo __('Action Name'); */?></span>
                </label>

                <div class="admin__field-control">
                    <input class="admin__control-text" type="text" name="module_name" id="codegen_module_name_create" maxlength="255">

                    <div class="admin__field-note">
                        <span><?php /*echo sprintf(__('Module name should match the following pattern: %s. Example <strong>Ibg_Codegen</strong>'), $block->getModuleNameRegEx()); */?></span>
                    </div>
                </div>
            </fieldset>-->
        </fieldset>
    </div>
</div>