<?php
/**
 * Created by PhpStorm.
 * User: Ion Bogatu
 * Date: 6/28/2018
 * Time: 5:21 PM
 */

/**
 * @var \Ibg\Codegen\Helper\ModuleGenerator $moduleGeneratorHelper
 * @var \Magento\Backend\Block\Template $block
 */
$moduleGeneratorHelper = $this->helper('\Ibg\Codegen\Helper\ModuleGenerator');
?>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "codegen": {
                        "component": "Ibg_Codegen/js/globalpage/codegen-bindings",
                        "currentModule": "<?php echo $moduleGeneratorHelper->getCurrentlySelectedModule() ? $moduleGeneratorHelper->getCurrentlySelectedModule() : '' ?>",
                        "children": {
                            "module": {
                                "component": "Ibg_Codegen/js/globalpage/codegen-module",
                                "showSuccessMessage": "<?php echo $moduleGeneratorHelper->getCurrentlySelectedModule() ? true : false; ?>",
                                "moduleList": <?php echo json_encode($moduleGeneratorHelper->getModuleList());?>
                            },
                            "controller": {
                                "component": "Ibg_Codegen/js/globalpage/codegen-controller",
                                "showSuccessMessage": "<?php echo $moduleGeneratorHelper->getCurrentlySelectedModule() ? true : false; ?>"
                            }
                        }
                    }
                }
            }
        }
    }
</script>
